language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1
  jobs:
    - FEATURES=""
    - FEATURES="async"

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo doc --verbose --features "$FEATURES" --no-deps
  - cargo test --verbose --features "$FEATURES"

matrix:
  include:
    - name: 'docs.rs simulation'
      rust: nightly
      env:
        - RUSTDOCFLAGS="--cfg docsrs"
      script:
        - cargo doc --no-deps --all-features
